### ISSUE TITLE
Chacha-x86.pl missing

### ISSUE THREAD

**Issue by xetorixik** [h-yamamo/openssl-chacha20poly1305#10]
Dear Ore sama,

First of all thanks for your patch.
Much appreciated.

About your patch, it seems that your patch is missing the Chacha-x86(.pl) part for x86 compatible machines.

Because your change log indicated that you have used multiple sources from Openssl and Boringssl.

Chacha-x86 is available at both upstream Openssl and Boringssl: https://github.com/google/boringssl/tree/master/crypto/chacha/asm
https://github.com/openssl/openssl/tree/master/crypto/chacha/asm

In contrast to Chacha, your Poly1305 implementation does contain the x86 file. 
So this issue seems a bug to me.

Please add Chacha-x86 support to your patch.
Thanks.

**Comment by h-yamamo** [comment]
The reason is https://github.com/h-yamamo/openssl-chacha20poly1305/commit/9d61bd26a74ec5714be567ac932840b96919da8d .

**Comment by xetorixik** [comment]
Thanks for your reply.
