### ISSUE TITLE
backport chacha20/poly1305 asm codes from openssl-1.1

### ISSUE THREAD

**Issue by h-yamamo** [h-yamamo/openssl-chacha20poly1305#5]

**Comment by h-yamamo** [comment]
[openssl-dev] [openssl.org #4439] poly1305-x86.pl produces incorrect output
http://rt.openssl.org/Ticket/Display.html?id=4439

**Comment by h-yamamo** [comment]
problem also armhf arch.
BoringSSL reverted.
https://boringssl.googlesource.com/boringssl/+/3c4a5cbb71453c5d61314a3f76a5ca6f123dbf94

**Comment by szepeviktor** [comment]
Do you use this commit?
https://github.com/openssl/openssl/commit/7dcb21869bec05d574d55e4c29daa5d58480d2a1

**Comment by h-yamamo** [comment]
I don't know this commit.
See https://github.com/h-yamamo/openssl-chacha20poly1305/blob/master/jessie/debian/changelog

**Comment by szepeviktor** [comment]
Thank you.

```
# git clone -b 1.0.2-aead git://git.openssl.org/openssl.git
Cloning into 'openssl'...
fatal: Remote branch 1.0.2-aead not found in upstream origin
```

https://github.com/h-yamamo/openssl-chacha20poly1305/blob/master/jessie/debian/changelog#L34-L35

**Comment by h-yamamo** [comment]
That branch was deleted.  I got in 2014.
If you want that source code, let me know.
...oops. I have only related source files.

**Comment by szepeviktor** [comment]
It would be nice to have the origin of the patches.

**Comment by h-yamamo** [comment]
I've found 1.0.2-aead branch.
https://github.com/ksophocleous/openssl

**Comment by szepeviktor** [comment]
Thank you!
Have you used this commit?
https://github.com/ksophocleous/openssl/commit/9a8646510b3d0a48e950748f7a2aaa12ed40d5e0

**Comment by h-yamamo** [comment]
It does not make sense.
You can inspect all sources - this repository from the initial, openssl 1.0.2-aead branch, boringssl and libressl.

**Comment by h-yamamo** [comment]
https://github.com/openssl/openssl/commit/6ca3e6e779635ac54d51efb3483b7616abfdf477
poly1305/asm/poly1305-x86_64.pl: not all assemblers manage << in constant.

--> No problem with gcc before this change

**Comment by h-yamamo** [comment]
match OpenSSL 1.1.0
