### ISSUE TITLE
symbols-file-contains-debian-revision

### ISSUE THREAD

**Issue by szepeviktor** [h-yamamo/openssl-chacha20poly1305#9]
Lintian warns about `symbols-file-contains-debian-revision`

> W: libssl1.0.0: symbols-file-contains-debian-revision on symbol OPENSSL_1.0.1s@OPENSSL_1.0.1s and 3 others

Please consider patching `debian/libssl1.0.0.symbols`.

**Comment by h-yamamo** [comment]
same message out with pure official package

**Comment by szepeviktor** [comment]
It must be a Debian bug.
